<#import "parts/htmlPad.ftlh" as pad>

<@pad.page "Alex Laptop Shop">
    <div class="col text-center">
        <div class="display-lg-1 display-3" style="color: #343a40">Доброго дня!</div>
        <div class="display-lg-1 display-3" style="color: #343a40">Раді бачити вас в Alex Laptop Shop!</div>
        <div class="display-lg-3 display-4" style="color: #343a40">Скористайтеся навігаційною панеллю для доступу до контролерів</div>
    </div>
</@pad.page>